phoenix-srun: job 4618375 queued and waiting for resources
phoenix-srun: job 4618375 has been allocated resources
phoenix-srun: Job 4618375 scheduled successfully!
Current QUOTA_TYPE is [reserved], which means the job has occupied quota in RESERVED_TOTAL under your partition.
Current PHX_PRIORITY is normal

[root] Loading dataset VisSim/folding_nets_2d_perception_test
Traceback (most recent call last):
  File "/mnt/petrelfs/haoyunzhuo/EMMA/EMMA_iccv/generate_response.py", line 164, in <module>
    main()
  File "/mnt/petrelfs/haoyunzhuo/EMMA/EMMA_iccv/generate_response.py", line 33, in main
    dataset = load_dataset(args.dataset_name, split=args.split)
  File "/mnt/petrelfs/haoyunzhuo/anaconda3/envs/gwen2_5/lib/python3.9/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
  File "/mnt/petrelfs/haoyunzhuo/anaconda3/envs/gwen2_5/lib/python3.9/site-packages/datasets/load.py", line 1853, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/mnt/petrelfs/haoyunzhuo/anaconda3/envs/gwen2_5/lib/python3.9/site-packages/datasets/load.py", line 1729, in dataset_module_factory
    raise e1 from None
  File "/mnt/petrelfs/haoyunzhuo/anaconda3/envs/gwen2_5/lib/python3.9/site-packages/datasets/load.py", line 1616, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({e.__class__.__name__})") from e
ConnectionError: Couldn't reach 'VisSim/folding_nets_2d_perception_test' on the Hub (LocalEntryNotFoundError)
phoenix-srun: error: SH-IDCA1404-10-140-54-36: task 0: Exited with exit code 1
phoenix-srun: launch/slurm: _step_signal: Terminating StepId=4618375.0
